### ISSUE TITLE
UnhandledError when saving chrome-bookmarks extension

### ISSUE THREAD

**Issue by sbeugen** [nortmas/chrome-bookmarks#8]
My Chrome-Bookmarks extension stopped working, so I tried to remove and add it again. 
When I try to save the extension I get following Error:

Message: 'com.github.nortmas.chrome-bookmarks'
Error Name: UnhandledError
Type: KeyError

Stacktrace:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 433, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.nortmas.chrome-bookmarks'
```

Pop_OS 20.04
Ulauncher v5.7.5

**Comment by sbeugen** [comment]
Updated to Ulaunvher v5.9.0 and it works again
